1:10.2.0+ds-1 (patches unapplied)
Imported using git-ubuntu import.

diff --git a/tests/lcitool/libvirt-ci/.gitlab-ci.yml b/tests/lcitool/libvirt-ci/.gitlab-ci.yml
--- a/tests/lcitool/libvirt-ci/.gitlab-ci.yml
+++ b/tests/lcitool/libvirt-ci/.gitlab-ci.yml
@@ -2,7 +2,7 @@
 # the upstream repo default branch. To force a run when pushing
 # to a feature branch use
 #
-#  git push -o ci.variable=RUN_PIPELINEI=1 ...
+#  git push -o ci.variable=RUN_PIPELINE=1 ...
 
 stages:
   - containers
@@ -85,6 +85,7 @@ stages:
   script:
     - source <(_venv_/bin/python3 bin/lcitool -d /tmp/datadir variables $NAME all_mappings | grep PKGS)
     - set +e
+    - ret=0
     - for pkg in $PKGS;
       do
         echo -n "Checking package '$pkg' ... ";
@@ -97,7 +98,7 @@ stages:
           echo "LAST ERROR:";
           echo "-----------";
           echo -e "$out";
-          exit 1;
+          ret=1;
         fi;
       done
 
@@ -113,7 +114,7 @@ stages:
           echo "LAST ERROR:";
           echo "-----------";
           echo -e "$out";
-          exit 1;
+          ret=1;
         fi;
       done
 
@@ -129,13 +130,20 @@ stages:
           echo "LAST ERROR:";
           echo "-----------";
           echo -e "$out";
-          exit 1;
+          ret=1;
         fi;
       done
+
+    - if [ $ret -ne 0 ];
+      then
+        echo "Some failures occurred. See above";
+        exit $ret;
+      fi;
+
   variables:
     CPAN_DRY_RUN_COMMAND: cpanm --scandeps
   rules:
-    - if: '$LIBVIRT_CI_SKIP_TARGET && $NAME =~ $LIBVIRT_CI_SKIP_TARGET'
+    - if: '$LIBVIRT_CI_SKIP_TARGET && $NAME =~ /$LIBVIRT_CI_SKIP_TARGET/'
       when: never
     - <<: *job_rules_merge_request
       <<: *job_rules_test_container_changes
@@ -194,7 +202,7 @@ check-dco:
   script:
     - ./containers/check-dco/check-dco.py
 
-flake8:
+linters:
   extends: .test_template
   stage: sanity_checks
   image: python:3.8-alpine
@@ -204,6 +212,18 @@ flake8:
     - python3 -m pip install tox
   script:
     - tox -e lint
+
+mypy:
+  extends: .test_template
+  stage: sanity_checks
+  image: python:3.8-alpine
+  needs: []
+  before_script:
+    - apk update
+    - apk add pkgconf libvirt-dev cairo-dev gcc musl-dev gobject-introspection-dev
+    - python3 -m pip install tox
+  script:
+    - tox -e mypy
 
 unittests:
   extends: .test_template
@@ -240,19 +260,19 @@ x86_64-check-almalinux-9:
     IMAGE: docker.io/library/almalinux:9
     NAME: almalinux-9
 
-x86_64-check-alpine-320:
-  extends: .check_container_template
-  variables:
-    <<: *apk_dry_run_command
-    IMAGE: docker.io/library/alpine:3.20
-    NAME: alpine-320
-
 x86_64-check-alpine-321:
   extends: .check_container_template
   variables:
     <<: *apk_dry_run_command
     IMAGE: docker.io/library/alpine:3.21
     NAME: alpine-321
+
+x86_64-check-alpine-322:
+  extends: .check_container_template
+  variables:
+    <<: *apk_dry_run_command
+    IMAGE: docker.io/library/alpine:3.22
+    NAME: alpine-322
 
 x86_64-check-alpine-edge:
   extends: .check_container_template
@@ -270,12 +290,13 @@ x86_64-check-centos-stream-9:
     IMAGE: quay.io/centos/centos:stream9
     NAME: centos-stream-9
 
-x86_64-check-debian-11:
+x86_64-check-centos-stream-10:
   extends: .check_container_template
+  allow_failure: true
   variables:
-    <<: *apt_dry_run_command
-    IMAGE: docker.io/library/debian:11-slim
-    NAME: debian-11
+    <<: *dnf_dry_run_command
+    IMAGE: quay.io/centos/centos:stream10
+    NAME: centos-stream-10
 
 x86_64-check-debian-12:
   extends: .check_container_template
@@ -283,6 +304,13 @@ x86_64-check-debian-12:
     <<: *apt_dry_run_command
     IMAGE: docker.io/library/debian:12-slim
     NAME: debian-12
+
+x86_64-check-debian-13:
+  extends: .check_container_template
+  variables:
+    <<: *apt_dry_run_command
+    IMAGE: docker.io/library/debian:13-slim
+    NAME: debian-13
 
 x86_64-check-debian-sid:
   extends: .check_container_template
@@ -292,19 +320,19 @@ x86_64-check-debian-sid:
     IMAGE: docker.io/library/debian:sid-slim
     NAME: debian-sid
 
-x86_64-check-fedora-40:
-  extends: .check_container_template
-  variables:
-    <<: *dnf_dry_run_command
-    IMAGE: registry.fedoraproject.org/fedora:40
-    NAME: fedora-40
-
 x86_64-check-fedora-41:
   extends: .check_container_template
   variables:
     <<: *dnf_dry_run_command
     IMAGE: registry.fedoraproject.org/fedora:41
     NAME: fedora-41
+
+x86_64-check-fedora-42:
+  extends: .check_container_template
+  variables:
+    <<: *dnf_dry_run_command
+    IMAGE: registry.fedoraproject.org/fedora:42
+    NAME: fedora-42
 
 x86_64-check-fedora-rawhide:
   extends: .check_container_template
